# Generated by Django 4.2.1 on 2023-05-04 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_remove_scope_is_main_remove_scope_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={},
        ),
        migrations.RemoveField(
            model_name='scope',
            name='articles',
        ),
        migrations.AlterField(
            model_name='tag',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope', to='articles.article'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='scope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope', to='articles.scope'),
        ),
    ]
