# Generated by Django 4.2.1 on 2023-05-14 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_alter_tag_article_alter_tag_scope'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='scope',
        ),
    ]
