# Generated by Django 4.2.1 on 2023-05-16 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_alter_tag_options_remove_tag_article_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scope',
            old_name='tags',
            new_name='tag',
        ),
    ]
